variables:
  IMAGE_NAME: tests
  ENV_TAG: v1
  DOCKER_FILE: ./docker/gitlab_ci/Dockerfile
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  XDEBUG_MODE: coverage

stages:
  - build
  - test
  - coverage

build_test_image:
  image: docker
  stage: build
  services:
    - docker:dind
  script: ./scripts/build-image.sh
  only:
    refs:
      - master
    changes:
      - docker/gitlab_ci/Dockerfile

tests:
  image: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$ENV_TAG
  stage: test
  script:
    - cp .env.test .env
    - composer config http-basic.spark.laravel.com $SPARK_USERNAME $SPARK_API_TOKEN
    - composer install
    - php artisan key:generate
    - php artisan test
    - ./vendor/bin/phpunit --coverage-text --colors=never -c phpunit.xml
  artifacts:
    expose_as: "Test reports"
    paths:
      - cobertura.xml
      - junit.xml
    reports:
      cobertura: cobertura.xml
      junit: junit.xml
  retry:
    max: 2
    when:
      - always

pages:
  image: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$ENV_TAG
  stage: coverage
  script:
    - cp .env.test .env
    - composer config http-basic.spark.laravel.com $SPARK_USERNAME $SPARK_API_TOKEN
    - composer install
    - php artisan key:generate
    - ./vendor/bin/phpunit --coverage-text --colors=never -c phpunit.xml
    - rm -rf ./public
    - cp -R reports/html/ ./public
  artifacts:
    paths:
      - public
    expire_in: 7 day
  needs:
    - tests
  only:
    - master
  retry:
    max: 2
    when:
      - always
