variables:
  IMAGE_NAME: tests
  ENV_TAG: v1
  DOCKER_FILE: ./docker/gitlab_ci/Dockerfile
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  XDEBUG_MODE: coverage

stages:
  - build
  - test
  - coverage

build_test_image:
  image: docker
  stage: build
  services:
    - docker:dind
  script: ./scripts/build-image.sh
  only:
    refs:
      - master
    changes:
      - docker/gitlab_ci/Dockerfile

tests:
  image: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$ENV_TAG
  stage: test
  script:
    - cp .env.test .env
    - composer install
    - php artisan key:generate
    - ./vendor/bin/phpunit --coverage-text --colors=never --testdox -c phpunit.xml
    - sed 's/filename="/filename="backend\/app\//' reports/cobertura.xml > reports/formated_cobertura.xml
    - sed 's/\/builds\/seelo\/pomodoro\/backend\/app/backend\/app\//' reports/formated_cobertura.xml > reports/formated_cobertura2.xml
  artifacts:
    expose_as: "test reports"
    paths:
      - reports/
    reports:
      cobertura: reports/formated_cobertura2.xml
      junit:
        - reports/junit.xml

pages:
  image: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$ENV_TAG
  stage: coverage
  script:
    - cp .env.test .env
    - composer install
    - php artisan key:generate
    - ./vendor/bin/phpunit --coverage-text --colors=never -c phpunit.xml
    - rm -rf ./public
    - cp -R reports/html/ ./public
  artifacts:
    paths:
      - public
    expire_in: 7 day
  needs:
    - tests
  only:
    - master
